### PR TITLE
Allow building with multiple 1.8.7 patchlevels

### PR DESCRIPTION
**Pull request by jonforums**
...a quick patch enabling me to build with 1.8.7-p334

### CODE REVIEW

**Comment by vertiginous** [comment]
Did you have to patch Exerb to build on p334?  If not I could just switch to building on that.

**Comment by jonforums** [comment]
I used the Exerb I built with p330.

Good point. Is it wise to count on Exerb working across multiple 1.8.7 patch levels, or should everything be built with the same version-patch? From what I've seen of pik's code so far, pik _should_ be ok, but I don't know enough about Exerb to give any feedback other than "...I don't want multiple 1.8.7's on my system."

**Comment by vertiginous** [comment]
I doubt anything changed between 330 and 334 that would break Exerb. I was planning to upgrade pik to it soon anyway. If you want to change it to only work on 334, I'm ok with that. I'll pull it in and test it out. 

Thanks!

**Comment by jonforums** [comment]
Are you OK with pulling the commit as-is to allow building with multiple 1.8.7 versions?

Since your post http://vert.igino.us/2011/01/05/exerb-101-building-windows-executables-with-ruby/ makes it so simple to understand how to build exerb, I expect/hope more people will start building both exerb and pik. If so, IMO, making pik buildable on multiple 1.8.7 patchlevels is a Good Thing assuming no subtle gotchas.

That said, I'll update the commit to whatever you think is best, just let me know.

**Comment by vertiginous** [comment]
I put that code there to prevent myself from building/releasing with the wrong version.  The more I think about it the less it worries me.  I'm fine with this the way it is.  I'll pull it in later today, hopefully.

**Comment by vertiginous** [comment]
merged.  Thanks so much, Jon.

**Pull request merged**
